[colors.primary]
background = "#fbf1c7"
foreground = "#3c3836"

[colors.normal]
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"

[colors.bright]
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
